DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NDc2ODIxMiwidXNlcklkIjoxfQ.XKkE5-k8g3Glgzqivfhlc--7PHnXmnhTPyY9FDx2a-c