DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0NDc2MTQ4MCwidXNlcklkIjoxfQ.g6p7K7Q7Wj-LSV2KcKs5TUbTeuZcPbGvnukyYRWbPlU